// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHVio8RdQvLd9QKbvTSGSKRRHMz1rdbU',
    appId: '1:79863535027:web:dc4f3d9f8225c230c9a7c6',
    messagingSenderId: '79863535027',
    projectId: 'karyaku-73bce',
    authDomain: 'karyaku-73bce.firebaseapp.com',
    storageBucket: 'karyaku-73bce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGIV3AfMO_pU11bz6_EhRixa32Z14e7s',
    appId: '1:79863535027:android:48e7398b3d52e108c9a7c6',
    messagingSenderId: '79863535027',
    projectId: 'karyaku-73bce',
    storageBucket: 'karyaku-73bce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodbgs1jkEK6GtzuMyTa_zFpOtOQlGtoU',
    appId: '1:79863535027:ios:ff93386cba594bcec9a7c6',
    messagingSenderId: '79863535027',
    projectId: 'karyaku-73bce',
    storageBucket: 'karyaku-73bce.appspot.com',
    iosBundleId: 'com.example.karyaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodbgs1jkEK6GtzuMyTa_zFpOtOQlGtoU',
    appId: '1:79863535027:ios:1853aec2e54559e4c9a7c6',
    messagingSenderId: '79863535027',
    projectId: 'karyaku-73bce',
    storageBucket: 'karyaku-73bce.appspot.com',
    iosBundleId: 'com.example.karyaku.RunnerTests',
  );
}
